name: Deploy Theme
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Build Theme
        uses: mikeal/npx@1.0.0
        with:
          args: "gulp build" 
      - name: Deploy Ghost Theme
        uses: TryGhost/action-deploy-theme@v1.4.0
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
          file: ghost-theme-lerk.zip
